version: 0.0
os: linux
files: 
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /test.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /test.sh
      timeout: 300
      runas: root      
